### ISSUE TITLE
[FEATURE] FastAPISessionMaker documentation

### ISSUE THREAD

**Issue by transfluxus** [dmontagu/fastapi-utils#4]
Hi is there an example somewhere on how to use the SessionMaker? 
Thank you!

**Comment by dmontagu** [comment]
Sorry I've been busy and haven't had time to finish the documentation, but I'll do this now!

**Comment by transfluxus** [comment]
nice, thanks for updating it.

**Comment by transfluxus** [comment]
I have questions related to your implementation. on the starlette and fastapi documentation is explains using database asycn. I guess that would look quite different here.

**Comment by dmontagu** [comment]
> starlette and fastapi documentation is explains using database asycn

I'm not sure what you mean by this, but you can't combine async database usage with sqlalchemy orm (and therefore sqlalchemy sessions). The implementation here is specifically for use with sqlalchemy orm, and if you want to use an async database driver you can, but then you just wouldn't need a sessionmaker anyway.

----

The reason I don't like using a middleware for sessions is that it adds some small overhead to every request even for endpoints that don't hit the database, and adds more response latency for requests involving the database that you don't expect to fail (since it lets you send a response before you perform the commit).

On top of that, the *only* benefit is that if the commit fails, you'll get a 500 error sent to the client instead of a 200. That's potentially useful for quickly identifying problems, but you can still handle (and log) the database exceptions coming from the contextmanager dependency, so it's not like this results in completely silent failures.

Also, to be clear, a commit/rollback will happen with this approach even if you don't do it manually, you just won't see a failure raised as a 500 error.

----

On top of that, if you are actually potentially expecting errors on the commit, it's probably better to handle it directly in your endpoint code so you can give a descriptive response about what went wrong.

**Comment by transfluxus** [comment]
Thanks for the explanation. I am hitting the the last point you are giving more and more and I agree that it make much more sense to handle the error exactly where it happens, ... in the endpoint method.

**Comment by dmontagu** [comment]
@transfluxus Glad to help.

And please continue to report any issues you run into, whether questions, or especially if you notice any performance issues or bugs!
